# docker push momonong/neuroai-backend:latest
# docker push momonong/neuroai-frontend:latest
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: momonong/neuroai-backend:latest
    container_name: neuroai_backend
    expose:
      - "8001"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - RUN_PIPELINE_AFTER_UPLOAD=false
    working_dir: /app/backend
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: momonong/neuroai-frontend:latest
    container_name: neuroai_frontend
    ports:
      - "55688:80"
    depends_on:
      - backend
    restart: unless-stopped
